### ISSUE TITLE
why? click inside also close the dialog

### ISSUE THREAD

**Issue by 12343954** [douglasjunior/react-native-simple-dialogs#1]
RT

**Comment by douglasjunior** [comment]
If the content is not touchable, it will capture the touch in the background :(

Try to put a Touchable (without onPress) wrapped around your content.

**Comment by 12343954** [comment]
oh，thank you，i will try，but it's not a good idea

**Comment by 12343954** [comment]
excuse me，i do what you said，warp the content with Touchable ，it's still close after click inside

**Comment by douglasjunior** [comment]
Sorry, is not a Touchable, is a ScrollView which should be wrapped.

This is a known problem in react-native. facebook/react-native#1046

**Comment by douglasjunior** [comment]
Fixed in `0.2.5`.
