### ISSUE TITLE
Android Back Button does not close the opened dialog box by default

### ISSUE THREAD

**Issue by rajeshzmoke** [douglasjunior/react-native-simple-dialogs#10]
When the user presses the back button in android the default behaviour should be to dismiss the dialog box but it does not happen..

**Comment by douglasjunior** [comment]
This `Dialogs` are created on top of `Modal` component.

When user press **Back Button**, the `Modal` emits the event `onRequestClose `. 

Take a look on the `Dialog` props list:

- [Dialog](https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/Dialog.js#L161)

And the [official `Modal` docs](https://facebook.github.io/react-native/docs/modal.html).

**Comment by rajeshzmoke** [comment]
thanks @douglasjunior
