### ISSUE TITLE
Dialog is not disappearing in ios

### ISSUE THREAD

**Issue by fazeelzama20** [douglasjunior/react-native-simple-dialogs#12]
Hello, I am using this library. It is working fine in android. Dialog are properly disappearing in it when I call `setState({
showProgress:false
})` But it is not disappearing on ios.

**Comment by douglasjunior** [comment]
This library uses the React Native `Modal` component internally https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/Dialog.js#L116

This problem is new to me.

**Comment by rajsatish4ar** [comment]
just add time-interval after
`setState({ showProgress:false })`
Like : 
`setState({ showProgress:false })
setTimeout(()=>{Alert.alert('messge')},2000)
`

**Comment by douglasjunior** [comment]
As @rajsatish4ar , for iOS you need a timeout when open a Modal just after close another one.
