### ISSUE TITLE
Can I add my Redux Form in our simple dialogs

### ISSUE THREAD

**Issue by XeCtvi** [douglasjunior/react-native-simple-dialogs#15]
Is that possible? I gave a try but showing a big empty content. :(

**Comment by douglasjunior** [comment]
This library uses React Native Modal component, so you can't mix Inputs inside and outside the Modal in the same redux-form.

**Comment by XeCtvi** [comment]
Hi @douglasjunior ,

Thanks for the reply, I will close the issue.
