### ISSUE TITLE
How to Remove default padding of dialog?

### ISSUE THREAD

**Issue by sandeepsinghs** [douglasjunior/react-native-simple-dialogs#21]
How do we remove default padding of dialog?

When I implement custom content dialog then there is large padding top and bottom. 

Please help to customize the style of dialog.

Thank you.

**Comment by douglasjunior** [comment]
You can use the props `contentStyle` and `dialogStyle`.

https://github.com/douglasjunior/react-native-simple-dialogs/blob/b880d352401da872cff03532a2048ad3be4be042/src/Dialog.js#L161-L176

**Comment by silkyland** [comment]
`
<Dialog
      contentStyle={{ margin: 0, padding: 0 }}
      .....
`

**Comment by alcristog** [comment]
According to popup-dialog-example/src/components/DialogContent.js, there is a default style you attach your custom style over:

```
const styles = StyleSheet.create({
  content: {
    paddingLeft: 18,
    paddingRight: 18,
    paddingBottom: 24
  }
});
```
So, in your code, you only have to override these parameters as follows:

```
<DialogContent
            style={{
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0
            }}
          >
```
Just consider that you have to style the _DialogContent_ component. Neither using _padding: 0_ nor styling with the _contentStyle_ attribute of the _Dialog_ component seem to work.

**Comment by douglasjunior** [comment]
> For anyone who is looking for a solution in 2024, in Dialog there is no props for contentStyle anymore and you can not overwrite this from the Dialog style, all what you need is to overwrite the Dialog Content or Dialog Action containers based on your need, each one of them have a default padding

You are wrong, my friend, we still have these props.

https://github.com/douglasjunior/react-native-simple-dialogs/blob/196ba4650c24f953e233cb135312ba0d0953c398/src/Dialog.tsx#L89-L98

https://github.com/douglasjunior/react-native-simple-dialogs/blob/196ba4650c24f953e233cb135312ba0d0953c398/src/Dialog.tsx#L195-L209

**Comment by Abdalrzakalsouki** [comment]
@douglasjunior thank you for correcting me, can I ask you what I am missing? becasue I can not find this in the docs or in the types when I open the Dialog component                                                                                                               
``` export type Props = {
  /**
   * Determines whether clicking outside the dialog dismiss it.
   */
  dismissable?: boolean;
  /**
   * Determines whether clicking Android hardware back button dismiss dialog.
   */
  dismissableBackButton?: boolean;
  /**
   * Callback that is called when the user dismisses the dialog.
   */
  onDismiss?: () => void;
  /**
   * Determines Whether the dialog is visible.
   */
  visible: boolean;
  /**
   * Content of the `Dialog`.
   */
  children: React.ReactNode;
  style?: Animated.WithAnimatedValue<StyleProp<ViewStyle>>;
  /**
   * @optional
   */
  theme?: ThemeProp;
  /**
   * testID to be used on tests.
   */
  testID?: string;
};```

**Comment by Abdalrzakalsouki** [comment]
@douglasjunior sorry I made a mistake with the package, it is "react-native-simple-dialog" while I was talking about 'react-native-paper"
