### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by prasad456** [douglasjunior/react-native-simple-dialogs#26]
How can I change the buttons color from blue to custom color?

**Comment by douglasjunior** [comment]
Try to use the `style` on the `Button` props.

https://github.com/douglasjunior/react-native-simple-dialogs#button-props

**Comment by ankitajmjb** [comment]
I am using react-native 'Button' component, its giving by default blue in color.

**Comment by ankitajmjb** [comment]
> Try to use the `style` on the `Button` props.
> 
> https://github.com/douglasjunior/react-native-simple-dialogs#button-props

Can you please explain how?

**Comment by douglasjunior** [comment]
The documentation is at the link.
