### ISSUE TITLE
Display dialog programmatically

### ISSUE THREAD

**Issue by sunviwo** [douglasjunior/react-native-simple-dialogs#32]
Is there any way to display dialog, confirm or progress dialog programmatically ? Something like ```dialog.show(param, param...)``` ? I'd like to us it in [Formik](https://github.com/jaredpalmer/formik) where it is not possible to reach and change state.

**Comment by douglasjunior** [comment]
Today is not, but is possible to add this feature.

I will love to revise a PR for this.

**Comment by douglasjunior** [comment]
This repository https://github.com/SNY7/react-native-dialog-layer uses react-native-simple-dialogs to open dialogs programatically, perhaps this can help with implementation.
