### ISSUE TITLE
how to change font  family in confirm dialogs button 

### ISSUE THREAD

**Issue by mossiiiiiii** [douglasjunior/react-native-simple-dialogs#36]
It doesn't change font family in confirm dialogs button, what is the solution?

**Comment by douglasjunior** [comment]
Take a look at https://github.com/douglasjunior/react-native-simple-dialogs#button-props

**Comment by mossiiiiiii** [comment]
> Take a look at https://github.com/douglasjunior/react-native-simple-dialogs#button-props

This solution can not be solved!

**Comment by douglasjunior** [comment]
_"This solution can not be solved!"_ doesn't help us to understand your problem. 

You need to set the font family in the `titleStyle`, inside the `positiveButton` or `negativeButton`. 

`titleStyle` accepts any props from https://facebook.github.io/react-native/docs/text-style-props. Including `fontFamily`.

If dont work, please show me your code.

**Comment by nicole-dsouza** [comment]
I'm having the same issue. I specified fontFamily in the titleStyle attribute, but it does not get reflected. Here is my code (only included relevant parts):

`
positiveButton={{
title: "Confirm",        
                        titleStyle: { fontFamily: "normal-r" }
                    }}
               `

**Comment by douglasjunior** [comment]
Hi @nicole-dsouza, the `titleStyle` is applied directly to the button's text style.


https://github.com/douglasjunior/react-native-simple-dialogs/blob/8c1c9f009bb2f0c5aa777b20ddd976da8c62ce8b/src/ConfirmDialog.js#L64

**Comment by nicole-dsouza** [comment]
Thanks @douglasjunior 

After going through ConfirmDialog.js I realized that my font wasn't working because the button text style had fontWeight: "bold" and I wasn't using a bold font. Removing that line fixed the issue.
