### ISSUE TITLE
Keyboard break the UI of dialog on Android

### ISSUE THREAD

**Issue by sandeepsinghs** [douglasjunior/react-native-simple-dialogs#39]
Hello,

I have implemented a custom dialog with TextInput. When the keyboard opens then the bottom view gets overlap and UI gets a break. So the TextInput view is also not visible properly.
![dialog_overlap](https://user-images.githubusercontent.com/14754191/63344492-34226900-c36e-11e9-8a02-9e5edae05425.PNG)

**Comment by harryharihar** [comment]
Remove height if you given to Dialog.js file.In my case i was given a height so keyboard break the ui.
 return (
            <View style={[{
                width: '100%',
                paddingBottom:10
                //height:'40%'
            }, contentStyle]}>
                {children}
            </View>
        )
