### ISSUE TITLE
Could not find a declaration file for module 'react-native-simple-dialogs'

### ISSUE THREAD

**Issue by maaliHasan** [douglasjunior/react-native-simple-dialogs#41]
Each time I install the library I got this compilation error :

Could not find a declaration file for module 'react-native-simple-dialogs'. 'c:/repos/rainbow-v2/rainbow-core/node_modules/react-native-simple-dialogs/index.js' implicitly has an 'any' type.

 Anyone could help with this error, Please.

**Comment by CarlosMayoralMX** [comment]
You are using TypeScript in your project? If so, you must create your own Type File. Have a look at:
https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/

**Comment by maaliHasan** [comment]
@CarlosMayoralMX  It works, Thanks
