### ISSUE TITLE
Fullscreen overlay not covering notch on iphoneX

### ISSUE THREAD

**Issue by unfrgivn** [douglasjunior/react-native-simple-dialogs#44]
First off, thank you for your work on this library. I'm having an issue with the Scrollview and iPhoneX. Unfortunately, I'm not well versed enough in this component to do more than guess & check. I cannot force the Scrollview to not have a vertical scroll unless I set "horizontal". I don't even know why it's scrolling vertically with the given props? I tried messing with a bunch of style props, SafeAreaViews and more, but didn't get anything solid. I would submit a PR to add props to the Scrollview or allow overriding the `style` | `contentContainerStyle` props, but again I don't have an elegant solution yet. 

It would also appear the default background color `backgroundColor: "#000000AA"` should exist on the ScrollView `style` to go edge-to-edge and not its content View for notched phones. You can see below the wrapper view background above/below the Scrollview content container. That may not be an issue if I can resolve the padding above and below the Scrollview on iPhoneX. 

Anyone have  thoughts or experience with this problem?

I tried to put this into a Snack but the devices don't have a notch so it won't show the issue 🤷‍♂️

**Dialog**
```
<View style={{flex: 1, backgroundColor: 'purple'}}>
    <Dialog
        title="title"
        visible={true}
        overlayStyle={{flex: 1, backgroundColor: '#777777'}}>
        <View>
            <Text>Test</Text>
        </View>
    </Dialog>
</View>
```
<img width="687" alt="Screen Shot 2019-12-14 at 12 03 03 PM" src="https://user-images.githubusercontent.com/1675472/70852717-6e0e0280-1e6a-11ea-8c20-fc834a324b48.png">
 
_There is a similar height padding below the scrollview on iPhoneX if you swipe up_

- What version of React Native? 0.59.10
- What version of the library? 1.2.1
- iOS/Android version? 13.0 and 10.3.1
- Did the problem happen after updating React Native? No
- Are you using the library for the first time? No

**Comment by unfrgivn** [comment]
Oh geez, when researching ScrollView issues on iPhoneX, I tried `contentInsetAdjustmentBehavior` but I was setting it to "false", not "never"

It would be great to add this but I don't know if it has negative effects for other devices? At a minimum, we could pass it as a prop?

Should I submit a PR @douglasjunior?

**Comment by unfrgivn** [comment]
And to clarify for anyone else stumbling upon this, `contentInsetAdjustmentBehavior="never"` does in fact fill the screen with the existing `overlayStyle` defaults, so my comment about possibly needing to modify the ScrollView styles is moot.

**Comment by douglasjunior** [comment]
Hi @unfrgivn, thank you for your feedback and research.

The `ScrollView` is used only to configure the `keyboardShouldPersistTaps` property, so I guess that is ok to set others values to the `contentInsetAdjustmentBehavior`.

I will take a look ASAP.

**Comment by unfrgivn** [comment]
https://github.com/douglasjunior/react-native-simple-dialogs/pull/45

**Comment by douglasjunior** [comment]
Closed by https://github.com/douglasjunior/react-native-simple-dialogs/commit/7725dc1c0e54c6af5ada343ea580738ec8a49185
