### ISSUE TITLE
Progress bar not showing correctly

### ISSUE THREAD

**Issue by Zeshan316** [douglasjunior/react-native-simple-dialogs#46]
- "react-native": "0.61.1"
- "react-native-simple-dialogs": "^1.2.1"
- Android 9
- We don't want to update RN version
- Yes

![IMG_20200507_171930](https://user-images.githubusercontent.com/8476605/81293705-2ee58580-9087-11ea-8e62-a5af5aaad3d0.jpg)

**Comment by douglasjunior** [comment]
Please, provide the code snippet that you have used to create the ProgressDialog.
