### ISSUE TITLE
Keyboard Blocking Confirm Dialog Buttons on iOS

### ISSUE THREAD

**Issue by akriger** [douglasjunior/react-native-simple-dialogs#5]
When using Confirm Dialog with an input, The negative and positive buttons are covered by the keyboard on iOS. On Android, the Confirm Dialog moves up out of the way of the keyboard.
![simulator screen shot - iphone 6 - 2017-12-01 at 12 05 46](https://user-images.githubusercontent.com/12530743/33494054-feb18228-d68f-11e7-8acf-28992816fadc.png)
![screenshot_1512147770](https://user-images.githubusercontent.com/12530743/33494057-ffcd1348-d68f-11e7-8179-6bc513297281.png)

**Comment by douglasjunior** [comment]
This is an expected behaviour on iOS apps. To avoid this you can use [react-native-keyboard-manager](https://github.com/douglasjunior/react-native-keyboard-manager).

**Comment by akriger** [comment]
thanks I will try that out.
