### ISSUE TITLE
Can't lowercase button titles on Android

### ISSUE THREAD

**Issue by loureirorg** [douglasjunior/react-native-simple-dialogs#51]
On Android, the buttons are always on uppercase. 

It is not possible to lowercase their titles, even applying a `textTransform: 'none'` to them.

Pull Request: https://github.com/douglasjunior/react-native-simple-dialogs/pull/52 

- What version of React Native?
0.62.2

- What version of the library?
1.3.0

- iOS/Android version?
Pixel 2 - Android 11 (R, API 30) - Emulated

- Are you using the library for the first time
Yes.

- What code snippet did you use?
```jsx
<ConfirmDialog
    title="Confirm Dialog"
    message="Are you sure about that?"
    visible={true}
    positiveButton={{
        title: "Yes",
        onPress: () => alert("Yes touched!"),
        titleStyle: {textTransform: 'none'},
    }}
    negativeButton={{
        title: "No",
        onPress: () => alert("No touched!")
    }}
/>
```

- What happens?
It shows `YES` (uppercase).

- What is expected?
To show `Yes`.

**Comment by loureirorg** [comment]
The issue is at this code:
```js
const title = OS === 'ios' ?
    button.title :
    button.title.toUpperCase();
```
https://github.com/douglasjunior/react-native-simple-dialogs/blob/master/src/ConfirmDialog.js#L102

I suggest doing the "default to uppercase on Android" with CSS instead of JS:
1) Change the above code to: `const title = button.title`;
2) Add line `textTransform: 'uppercase'` after https://github.com/douglasjunior/react-native-simple-dialogs/blob/master/src/ConfirmDialog.js#L81;

**Comment by 1Ajay** [comment]
is it resolved?

**Comment by douglasjunior** [comment]
Fixed in https://github.com/douglasjunior/react-native-simple-dialogs/releases/tag/1.4.0
