### ISSUE TITLE
How remove the space bottom of popup if we are not using positive or negative buttons in Android only

### ISSUE THREAD

**Issue by sandeepg1220** [douglasjunior/react-native-simple-dialogs#53]
I'm getting more space at the place of positive or negative button as I am not using these buttons.
- What version of React Native?
React-native : 0.62.1
- What version of the library?
1.3.0
- iOS/Android version?
In all Android versions. iOS working fine
- Did the problem happen after updating React Native?
No
- Are you using the library for the first time?
No
- What code snippet did you use?
<ConfirmDialog
            visible={this.state.imageSuccessVisible}
            onTouchOutside={this.SubmitPressOutside}
            dialogStyle={homeStyles.popupView}
            >
            <View>
            <UploadSuccessImage style={homeStyles.dialoglogo} />
            <Text style={homeStyles.dialoglogo}>
            Image uploaded successfully
                </Text>
                <View style={{marginTop:20}}>
                <SemiUIRoundedButton event={this.onPressOkay}>
                <Text style={homeStyles.textStyle}>Okay</Text>
              </SemiUIRoundedButton>
              </View>
            </View>
        </ConfirmDialog>

**Comment by douglasjunior** [comment]
You can use the `Dialog` component and customize your own content.
