### ISSUE TITLE
How to create a global dialog?

### ISSUE THREAD

**Issue by Jarzka** [douglasjunior/react-native-simple-dialogs#54]
Hi

It looks like React Native Simple Dialogs is used as component in JSX. What happens if I want to use a specific dialog everywhere in my application, i.e. I want to create a global dialog that can be shown with a function call, no matter which view I'm looking? Is this possible?

I'm using React Native Navigation, which means that there is no single root component where I could put the dialog's JSX code, but instead there are multiple possible root components which can be set.

EDIT: My current solution is to include a specific "global components" component in every root component. This global components component contains the progress bar. I can turn the progress bar of by changed the state of the application. I wonder if there is a better way to do this.

**Comment by douglasjunior** [comment]
It is currently not possible. You would need to implement something like https://github.com/SNY7/react-native-dialog-layer

Duplicate #32
