### ISSUE TITLE
Set max width of ProgressDialog

### ISSUE THREAD

**Issue by Jarzka** [douglasjunior/react-native-simple-dialogs#55]
Hi

It seems that the width of ProgressDialog is 100% by default. It looks a bit too big on a tablet, especially on landscape mode.

How do I limit the width of the ProgressDialog? It seems that only the activity indicator can be styled via props, not the dialog itself.

**Comment by udarts** [comment]
I am using the following code to set the width for the dialog, as that works (dialogStyle is also documented):

    dialogStyle={{alignSelf: 'center',width: '50%'}}

**Comment by Jarzka** [comment]
Works. Thanks!
