### ISSUE TITLE
Hide Title Section from dialog

### ISSUE THREAD

**Issue by nidhinprathap** [douglasjunior/react-native-simple-dialogs#59]
How to hide the title section for a Custom Dialog? Is there an option or flag that can do that?

**Comment by douglasjunior** [comment]
Try:

```js
titleStyle={{
  padding: 0,
  margin: 0,
  height: 0,
  width: 0,
}}
```

**Comment by douglasjunior** [comment]
Btw, you can pass `title={null}`.

https://github.com/douglasjunior/react-native-simple-dialogs/blob/9136d5d569038b85d0a8d90ea9323811c66b7ffa/src/Dialog.js#L60

**Comment by nidhinprathap** [comment]
Thanks did make it work like that, sorry did update here. May be this can be added in ReadMe or a property can be exposed to disable header. Suggest a suggestion.

**Comment by douglasjunior** [comment]
Thanks for the feedback, but I dont think that this need to be documented.

You just need to "omit" the title prop, it's intuitive.

![image](https://user-images.githubusercontent.com/1512341/120086848-f0b76b80-c0b8-11eb-9920-b8857a7503f2.png)
