### ISSUE TITLE
Add possibility to change borderRadius of Dialog

### ISSUE THREAD

**Issue by remicoges** [douglasjunior/react-native-simple-dialogs#6]
Hello,

Currently, the Dialog borderRadius is hard-coded and not linked with the props, is there a possibility to currently do it or is it possible to add this feature ?

Thanks !

**Comment by douglasjunior** [comment]
Use `dialogStyle`.

```jsx
<Dialog dialogStyle={{borderRadius: 10}} >
...
</Dialog>
```
