### ISSUE TITLE
Feature Request: Add new type of 'slide' animation that doesn't also slide the background

### ISSUE THREAD

**Issue by hb-webdev** [douglasjunior/react-native-simple-dialogs#60]
I feel it looks a bit unappealing for the dark background to slide up over the screen contents along with the dialog. Can you please add a different 'slide' animation type where the background gets applied to the whole screen separately while the dialog slides in? (named something like `'slide-bgPop'`)

It would be extra cool if there was also an animation type where the background color faded in/out while the dialog slid in/out (named something like `'slide-bgFade'`).

Sorry no PR...this will be in the back of my mind, however...

**Comment by douglasjunior** [comment]
The animation is provided by [React Native Modal](https://reactnative.dev/docs/modal).

https://github.com/douglasjunior/react-native-simple-dialogs/blob/9136d5d569038b85d0a8d90ea9323811c66b7ffa/src/Dialog.js#L118-L119

And because of that, everything inside Modal will be automatically animated.
