### ISSUE TITLE
How to hide the statusBar when dialog shown

### ISSUE THREAD

**Issue by ronuelbmoralita** [douglasjunior/react-native-simple-dialogs#66]
Hi Sir, are there any props to hide the status bar when the dialog is open? I found statusBarTranslucent in React native it works perfectly, I hope there are available props that  I will use to hide the status bar using your Library. Thanks

"react-native": "0.71.3",
"react-native-simple-dialogs": "^1.5.0",
Android Q/ 10
- <Dialog
    visible={this.state.dialogVisible}
    title="Custom Dialog"
    onTouchOutside={() => this.setState({dialogVisible: false})} >
    <View>
        // your content here
    </View>
</Dialog>

![Screenshot_20230416_211521_com pasada](https://user-images.githubusercontent.com/75823435/232314776-2e84fd9b-35bb-4228-8143-b3e98fc3ca3a.png)

**Comment by douglasjunior** [comment]
Added `statusBarTranslucent` in version 2.0.0 

https://github.com/douglasjunior/react-native-simple-dialogs/releases/tag/2.0.0
