### ISSUE TITLE
How to fix or correctly align content inside dialog when using flexDirection="row" props

### ISSUE THREAD

**Issue by ronuelbmoralita** [douglasjunior/react-native-simple-dialogs#67]
Hi Sir, It's me again. I'm using Flexbox component with props flexDirection="row" inside your wonderful library react-native-simple-dialogs. But it seems my content is not aligned perfectly as you can see in my screenshot. I did all the styling but had no luck. Thank you in advance for your response.

- "react-native": "0.71.3"
-  "react-native-simple-dialogs": "^2.0.1"
- Android 10 or Q
- No
- No

![Screenshot_20230418_181757_com pasada](https://user-images.githubusercontent.com/75823435/232751776-385bdbbb-c445-435b-a025-15c4c9cd4314.jpg)

**Comment by douglasjunior** [comment]
This is not related to the library.

You will need to apply search about flexShring and flexGrown, and apply it to your Texts.

**Comment by ronuelbmoralita** [comment]
I see, then I will do my research more. Anyway, I really appreciate your response Sir. Thank you again. God bless you and your Family.
