### ISSUE TITLE
Encountered extra views at the top during customization

### ISSUE THREAD

**Issue by TallNutAlt** [douglasjunior/react-native-simple-dialogs#71]
`<Dialog
        visible={true}
        animationType={'fade'}
        contentStyle={{padding: 0, borderWidth: 0, justifyContent: 'center'}}
        dialogStyle={{
          borderRadius: 5,
          borderWidth: 0,
          padding: 0,
        }}
        overlayStyle={{justifyContent: 'center', alignItems: 'center'}}
        onTouchOutside={() => nextTypeStateClick(false)}>
        <View
          style={{
            backgroundColor: '#fff',
            width: moderateScale(300),
            borderWidth:1,
          }}>`
          
![efb579ea5cc7b22fec8b3c6fc119172](https://github.com/douglasjunior/react-native-simple-dialogs/assets/109561878/c7737e51-4b96-46b9-b03d-ecbed3ead23f)
如图所示顶部多了一部分视图

**Comment by TallNutAlt** [comment]
`const renderContent = () => {
        return (react_1.default.createElement(react_native_1.View, { style: [
                {
                    width: '100%',
                    flexShrink: 1,
                    padding: 24,
                    paddingTop: 20,
                },
                contentStyle,
            ] }, children));
    };`
    
    I think contentStyle should be given a default value instead of operating in style

**Comment by douglasjunior** [comment]
You need to set `paddingTop: 0`.
