### ISSUE TITLE
Any plans to expand API documentation?

### ISSUE THREAD

**Issue by greenais** [douglasjunior/react-native-simple-dialogs#8]
First - it's nice ans simple lib, thank you for definitely great job.
Probably adding some more detailed documentation could make it more straightforward usable and more popular.

Styling props list I've found in issues (heh), but what options are available for animationType prop?

**Comment by douglasjunior** [comment]
Today the props list can be found in `propTypes`:

- [Dialog](https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/Dialog.js#L161)

- [ProgressDialog](https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/ProgressDialog.js#L52)

- [ConfirmDialog](https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/ConfirmDialog.js#L183)

I think that a props list [like this](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) in README will be great. But I'm very busy now, any help will be welcome.

**Comment by douglasjunior** [comment]
Fixed by #22
