### ISSUE TITLE
Why ConfirmDialog so slow?

### ISSUE THREAD

**Issue by 1c7** [douglasjunior/react-native-simple-dialogs#9]
using React Native 0.51

### Problem: Click "No" the box disappear pretty quick,
but Click "Yes" it would freeze for 3 second then disappear

```javascript
import { ConfirmDialog } from 'react-native-simple-dialogs';

export default class LogsScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = { 
      remove_confirm_dialog_visible: false,
    };
  }
  _delete_log(){
  }
  render(){
    <ConfirmDialog
      title="Hint"
      message="Confirm delete?"
      visible={this.state.remove_confirm_dialog_visible}
      onTouchOutside={() => this.setState({ remove_confirm_dialog_visible: false })}
      positiveButton={{
        title: "Yes",
        onPress: () => {
          this.setState({ remove_confirm_dialog_visible: false });
          this._delete_log();
        }
      }}
      negativeButton={{
        title: "No",
        onPress: () => {
          this.setState({ remove_confirm_dialog_visible: false });
        }
      }}
    />
   }
}
```
  
not complete code of course, only  important part

**Comment by 1c7** [comment]
I am uploading a youtube video for demo

**Comment by douglasjunior** [comment]
The library uses Modal offered by React Native, no other operation is performed.

Possibly you have many elements on the screen that are slow to render. But I believe that the problem should only happen in development mode. Did you test in production?

**Comment by 1c7** [comment]
https://www.youtube.com/watch?v=eq9mR_zAc6U&feature=youtu.be

**Comment by 1c7** [comment]
no, I haven't test in production,
I connect my phone to computer than run `react-native run-android`

**Comment by 1c7** [comment]
since all I need is very simple confirm dialog,
I am switching to "Alert" provide by React Native
https://facebook.github.io/react-native/docs/alert.html

I would update after I got some result (got better performance or not)

**Comment by 1c7** [comment]
Thanks!

**Comment by douglasjunior** [comment]
Ok.

I believe `this._delete_log();` must perform some heavy operation to render. But in production this should not occur.

Here are some tips here: https://facebook.github.io/react-native/docs/performance.html

**Comment by douglasjunior** [comment]
Look, Dialog is only a `Modal` with some content:

https://github.com/douglasjunior/react-native-simple-dialogs/blob/1e6e894e2f0a03a92c511f56e782b397bece1de6/src/Dialog.js#L116-L124

**Comment by 1c7** [comment]
@douglasjunior Thank you very much! 
I would close issue now

**Comment by 1c7** [comment]
`this._delete_log();`
only remove item from an array of object(~40 object)

```

  _delete_log(){
    const logs_array = this.state.logs;
    var result = logs_array.filter(function (e) {
      return e[4] !== fid
    });
    this.setState({ logs: result });
  }

```

also, turn out the top right corner "Show Perf Monitor" also impact performance quite a lot

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/34722514-35c864a0-f582-11e7-845e-921972ec6d72.png)

I am just posting bit more info here

**Comment by douglasjunior** [comment]
Your list is long? FlatList have has poor performance for re-rendering in development mode.

**Comment by 1c7** [comment]
@douglasjunior oh, I didn't know that, Thanks for telling me,
I suppose once I pack it up as 'apk' it would get better performance
I am a newbie RN developer, building my second app. 
(both app target China market, so you can't find it on Play Store)

Thanks again!
